waveform = phased.LinearFMWaveform('SampleRate',1e6,...
    'PulseWidth',50e-6,'PRF',10e3,...
    'SweepBandwidth',100e3,'SweepDirection','Up',...
    'Envelope','Rectangular',...
    'OutputFormat','Pulses','NumPulses',1);

waveform = phased.LinearFMWaveform('PulseWidth',100e-6,...
    'SweepBandwidth',200e3,'PRF',4e3);

figure; plot(waveform); 

y_lfm = waveform();  % now can evaluate circularity signals